### ISSUE TITLE
File not found Exception

### ISSUE THREAD

**Issue by alihit96** [brownsoo/flutter_video_list_sample#2]
When I attempt to open the video why am I getting this error?
```
I/ExoPlayerImpl(17600): Init 97317e6 [ExoPlayerLib/2.9.6] [WSP_sprout, Nokia 2.2, HMD Global, 29]
E/GraphicExt(17600): GraphicExtModuleLoader::CreateGraphicExtInstance false
E/ExoPlayerImplInternal(17600): Source error.
E/ExoPlayerImplInternal(17600): com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/embed/dirin2.mp4
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:98)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(17600):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(17600):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(17600):         at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(17600): Caused by: java.io.FileNotFoundException: flutter_assets/embed/dirin2.mp4
E/ExoPlayerImplInternal(17600):         at android.content.res.AssetManager.nativeOpenAsset(Native Method)
E/ExoPlayerImplInternal(17600):         at android.content.res.AssetManager.open(AssetManager.java:828)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:79)
E/ExoPlayerImplInternal(17600):         ... 7 more
E/flutter (17600): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/embed/dirin2.mp4, null)
E/flutter (17600):
E/ExoPlayerImplInternal(17600): Source error.
E/ExoPlayerImplInternal(17600): com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/embed/dirin2.mp4
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:98)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal(17600):         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/ExoPlayerImplInternal(17600):         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/ExoPlayerImplInternal(17600):         at java.lang.Thread.run(Thread.java:919)
E/ExoPlayerImplInternal(17600): Caused by: java.io.FileNotFoundException: flutter_assets/embed/dirin2.mp4
E/ExoPlayerImplInternal(17600):         at android.content.res.AssetManager.nativeOpenAsset(Native Method)
E/ExoPlayerImplInternal(17600):         at android.content.res.AssetManager.open(AssetManager.java:828)
E/ExoPlayerImplInternal(17600):         at com.google.android.exoplayer2.upstream.AssetDataSource.open(AssetDataSource.java:79)
E/ExoPlayerImplInternal(17600):         ... 7 more
E/flutter (17600): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(VideoError, Video player had error com.google.android.exoplayer2.ExoPlaybackException: com.google.android.exoplayer2.upstream.AssetDataSource$AssetDataSourceException: java.io.FileNotFoundException: flutter_assets/embed/dirin2.mp4, null)
```

**Comment by brownsoo** [comment]
This is IO exception. please check file pathes and pubspec.
